export enum EventType {
    NEW_BOARD = 'NEW_BOARD',
    HIGHLIGHT_CELL = 'HIGHLIGHT_CELL',
    CELL_VALUE = 'CELL_VALUE',
    TOGGLE_CELL_NOTE = 'TOGGLE_CELL_NOTE',
    CLEAR_CELL_NOTES = 'CLEAR_CELL_NOTES',
    TOGGLE_LT_CONSTRAINT = 'TOGGLE_LT_CONSTRAINT',
    TOGGLE_NUMERIC_MODE = 'TOGGLE_NUMERIC_MODE',
}
